# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= LocalConfig.resolve('SECRET_KEY_BASE', '84fbcd8d557569eebfde4f4b403e33202b664bca97152fcb75800daca3a0c367aed404a0fcb3761769435ab641f7bbea8f487cccd633e099932cb3a45455c23e') %>

test:
  secret_key_base: <%= LocalConfig.resolve('SECRET_KEY_BASE', '20502f72c81ae258a3d15b682cabf64b2f60d83e5a3602314f0cb318c86109026db36365d276ff141f67912d39e54ffdd7c307cc82303af8ceba8df960c85936') %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= LocalConfig.resolve('SECRET_KEY_BASE') %>
